name: Samannen

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -  uses: docker/build-push-action@v3
         with:
           context: .
           registry: ghcr.io
           username: "eirikandre"
           password: ${{ secrets.PUSH_TOKEN }}
           repository: eirikandre/samannen
           tags: 1.0.0