name: Samannen

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: eirikandre/samannen:latest
          secrets: |
            GIT_AUTH_TOKEN=${{ secrets.PUSH_TOKEN }}